version: '3.8'

services:

  #nginx
  server:
    image: 'nginx:stable-alpine'
    container_name: server_nutrifood
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  #node
  npm:
    image: node:14
    container_name: node_nutrifood

  #php
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php_nutrifood
    volumes:
      - ./:/var/www/html

  #composer
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    container_name: composer_nutrifood
    volumes:
      - ./:/var/www/html

  #symfony
  symfony:
    build:
      context: ./dockerfiles
      dockerfile: symfony.dockerfile
    container_name: symfony_nutrifood
    volumes:
      - ./:/var/www/html

  #mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_nutrifood
    env_file:
      - ./env/mysql.env


  #GUI pour base de donnée
  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_nutrifood
    ports:
      - '8080:80'
    env_file:
      - ./env/phpmyadmin.env
    depends_on:
      - mysql