version: '3.8'

services:

  #nginx
  server:
    image: 'nginx:stable-alpine'
    container_name: server_sharemoumouth
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./etc/artifact/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  #node
  npm:
    image: node:14
    container_name: node_nutrifood

  #php
  php:
    build:
      context: etc/artifact/dockerfiles
      dockerfile: php.dockerfile
    container_name: php_sharemoumouth
    volumes:
      - ./:/var/www/html

  #composer
  composer:
    build:
      context: etc/artifact/dockerfiles
      dockerfile: composer.dockerfile
    container_name: composer_sharemoumouth
    volumes:
      - ./:/var/www/html

  #symfony
  symfony:
    build:
      context: etc/artifact/dockerfiles
      dockerfile: symfony.dockerfile
    container_name: symfony_sharemoumouth
    volumes:
      - ./:/var/www/html

  #postgresql
  postgresql:
    image: postgres
    container_name: postgres_shareMoumouth
    environment:
      POSTGRES_DB: shareMoumouth
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  #PgAdmin
  pgadmin:
    image: dpage/pgadmin4:5.6
    container_name: pgadmin_shareMoumouth
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - postgresql
